camera_topic: /aravis_cam1/image_color
radar_topic: /radar1/point_cloud_object
radar_prefix: /radar1
track_topic: /traffic_track1
detection_prefix: /detection1
control_prefix: /control1
final_topic: /traffic_final1
mqtt_enable: false
bev_enable: true
bev_image_path: BEV_test/ARTC20251029.png
fps: 20
stats_interval_seconds: 15
radar_track_enabled: false
optimize: true
model_enabled: true
model:
  modality: camera
  path: yolo11x.pt
  config_path: configs/rtdetr/rtdetr_r50vd_6x_coco.yml
  checkpoint_path: configs/checkpoints/checkpoint0035.pth
  conf_thresh: 0.65
  classes:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
camera:
  extrinsic_matrix:
  - - -0.007764782634083243
    - -0.9999427949580677
    - 0.0073590405062597996
    - 0.06361330985766236
  - - -0.18474366580433396
    - -0.005798078773533884
    - -0.9827696660068258
    - 5.238843382017464
  - - 0.9827560834100821
    - -0.008990528483165732
    - -0.18468807243491397
    - -0.882817984823344
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  camera_matrix:
  - - 2413.911679
    - 0.0
    - 1059.332971
  - - 0.0
    - 2161.173075
    - 745.776449
  - - 0.0
    - 0.0
    - 1.0
  width: 2048
  height: 1536
