camera_topic: /cam2_decompressed
radar_topic: /radar2/point_cloud_object
radar_prefix: /radar2
track_topic: /traffic_track2
detection_prefix: /detection2
control_prefix: /control2
final_topic: /traffic_final2
mqtt_enable: false
bev_enable: true
bev_image_path: BEV_test/ARTC20251029.png
fps: 20
stats_interval_seconds: 15
radar_track_enabled: false
optimize: true
model_enabled: true
model:
  modality: camera
  path: yolo11x.pt
  config_path: configs/rtdetr/rtdetr_r50vd_6x_coco.yml
  checkpoint_path: configs/checkpoints/checkpoint0035.pth
  conf_thresh: 0.65
  classes:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
camera:
  extrinsic_matrix:
  - - -0.0032373748122348296
    - -0.9894588150597806
    - 0.14477825143060571
    - -0.03456065953099054
  - - -0.32453545948057627
    - -0.13590297546428373
    - -0.9360593688788393
    - 4.6096221490560945
  - - 0.945868014329813
    - -0.05001605165293063
    - -0.32067451144633313
    - -0.5579465481685669
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  camera_matrix:
  - - 2413.911679
    - 0.0
    - 1059.332971
  - - 0.0
    - 2161.173075
    - 745.776449
  - - 0.0
    - 0.0
    - 1.0
  width: 2048
  height: 1536
